### PR TITLE
Release 0.12.0

### PR DESCRIPTION
**Pull request by mattwthompson**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mattwthompson** [comment]
@conda-forge-admin, please rerender

**Comment by mattwthompson** [comment]
I don't think there are substantive changes not already captured here: https://github.com/openforcefield/openff-toolkit/compare/0.11.4...0.12.0

**Review by j-wags — APPROVED** [review]
Just compared to the changes in https://github.com/openforcefield/openff-toolkit/pull/1488/files#diff-1fbd3f1fb4002bd59bde4c5b1501a1ac0a580dd70b9bcf05cfb35ef066e4b0f9 and everything here looks good. Thanks @mattwthompson!

**Comment by mattwthompson** [comment]
Thanks!

**Pull request merged**
