### PR TITLE
Remove `zstandard` pin

### PR DESCRIPTION
**Pull request by mattwthompson**
#86 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mattwthompson** [comment]
@conda-forge-admin, please rerender

**Comment by j-wags** [comment]
Should I expect to see `PYTHON_ZSTANDARD_IMPORT_POLICY='cffi_fallback'` somewhere?

**Comment by mattwthompson** [comment]
Nope, we don't build or test against OpenEye here

**Comment by j-wags** [comment]
Won't users with OE installed just get the error again then?

**Comment by mattwthompson** [comment]
Maybe, but they should use the CFFI fallback instead of us downpinning to a very old version of an upstream (that we don't use)

**Comment by j-wags** [comment]
Many of our partner companies run with the OE backend and it's very bad if they wake up one day to find their OpenFF workflows don't work any more (it wastes their time, erodes support for renewing, and makes them less inclined to install the latest versions).

I have three thoughts on how to proceed, but could use more info:
* Is OE clearly violating a packaging standard by [bundling zstandard](https://github.com/conda-forge/openff-toolkit-feedstock/issues/86#issuecomment-2250508090)/would we have leverage to ask them to change their packages?
* Can we or MolSSI incorporate an [internal fix](https://github.com/openforcefield/openff-toolkit/pull/1906#event-13490172142) to activate the CFFI workaround without causing broader harm?
* If neither of the above works, we'll need to document the workaround well and yell it from the mountaintops to soften the blow on our partner companies.

**Comment by mattwthompson** [comment]
I have no visibility into OpenEye's build process, but the environment they used in their most recent release is [unchanged from several months ago and quite out of date](https://github.com/conda-forge/openff-toolkit-feedstock/issues/86#issuecomment-2250508090) for no obvious reason and aware of this issue we reported. OpenEye Support told us on 5/2/24 that "Since there is a workaround, it is unlikely this will be fixed for the next toolkit release" so I have no idea if they intend to fix this or when

There's no a solution without violating best practices - setting users' environment variables, importing packages they don't need, etc.

**Pull request closed without merging**
