### PR TITLE
0.14.2 build 0

### PR DESCRIPTION
**Pull request by j-wags**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by j-wags** [comment]
@conda-forge-admin, please rerender

**Comment by mattwthompson** [comment]
The toolkit is now Pydantic v2 compatible and the `run_constrained` can be loosed now. (It can also be loosed in the future, of course)

**Review by mattwthompson — APPROVED** [review]
I don't think any changes are needed - the Python constraint is already loose and our upstreams should all support 3.11

**Comment by j-wags** [comment]
Can I remove the pydantic pin entirely? Or should I keep the lower bound?

**Comment by j-wags** [comment]
Checking the history, I get the sense that we can remove the pin entirely.

**Comment by mattwthompson** [comment]
Yes you're right - though I'd prefer `pydantic <3.0.0a0` if you're open that. Completely dropping the pin should work fine for a year or two as well.

The v1 backdoor is allegedly going away in v3. While it might seem far away, I think it's better to keep our upstreams constrained to MAJOR versions we trust sooner than later.

**Pull request merged**
