### PR TITLE
0.11.4

### PR DESCRIPTION
**Pull request by j-wags**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mattwthompson** [comment]
Could we sneak `importlib_metadata >=4.10` into the `run_constrained:` section of the base package?

There's some confusion in the feedstocks related to `importlib_metadata` vs. `importlib-metadata`; one [mirrors](https://anaconda.org/conda-forge/importlib-metadata/files) the other now but, unfortunately, there was a period in time in [which both existed](https://github.com/conda-forge/importlib-metadata-feedstock/issues/2) as parallel feedstocks. For mysterious reasons, specifying one but not the other can sometimes [bring in too-old-to-be-used builds](https://github.com/openforcefield/openff-bespokefit/pull/202#issuecomment-1314112832). Most packages use the hyphenated version, but `basis_set_exchange` has a [dependency](https://github.com/conda-forge/argcomplete-feedstock/blob/7146e8fab042b1c0d4b1450ffca58dc182a86b9e/recipe/meta.yaml#L25) that's pulling down an ancient and incompatible version (1.5). Adding this constraint into the base recipe should fix that without obvious new incompatibilities.

**Comment by j-wags** [comment]
Yup! I've added the pin.

**Comment by mattwthompson** [comment]
Thanks!

**Review by mattwthompson — APPROVED** [review]
LGTM once the new build finishes

**Pull request merged**
