### PR TITLE
Release 0.11.0rc1

### PR DESCRIPTION
**Pull request by mattwthompson**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mattwthompson** [comment]
@conda-forge-admin, please rerender

**Comment by mattwthompson** [comment]
@conda-forge-admin, please rerender

**Comment by mattwthompson** [comment]
So everything ran fine up until the last step in the test script in which `ForceField.create_openmm_system` is called:


```
2022-07-01T19:53:30.9414329Z + python test_openff_toolkit.py
2022-07-01T19:53:31.7431402Z Warning: Unable to load toolkit 'OpenEye Toolkit'. The Open Force Field Toolkit does not require the OpenEye Toolkits, and can use RDKit/AmberTools instead. However, if you have a valid license for the OpenEye Toolkits, consider installing them for faster performance and additional file format support: https://docs.eyesopen.com/toolkits/python/quickstart-python/linuxosx.html OpenEye offers free Toolkit licenses for academics: https://www.eyesopen.com/academic-licensing
2022-07-01T19:53:31.7922040Z {'The RDKit': '2022.03.3', 'AmberTools': '22.0', 'Built-in Toolkit': None}
2022-07-01T19:53:32.3448200Z Traceback (most recent call last):
2022-07-01T19:53:32.3450608Z   File "/home/conda/feedstock_root/build_artifacts/openff-toolkit-split_1656704812577/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/openff/utilities/utilities.py", line 69, in wrapper
2022-07-01T19:53:32.3452396Z     importlib.import_module(package_name)
2022-07-01T19:53:32.3453983Z   File "/home/conda/feedstock_root/build_artifacts/openff-toolkit-split_1656704812577/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/importlib/__init__.py", line 126, in import_module
2022-07-01T19:53:32.3464569Z     return _bootstrap._gcd_import(name[level:], package, level)
2022-07-01T19:53:32.3465525Z   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2022-07-01T19:53:32.3466118Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2022-07-01T19:53:32.3466734Z   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
2022-07-01T19:53:32.3467721Z ModuleNotFoundError: No module named 'openff.interchange'
2022-07-01T19:53:32.3468093Z 
2022-07-01T19:53:32.3468549Z During handling of the above exception, another exception occurred:
2022-07-01T19:53:32.3469162Z 
2022-07-01T19:53:32.3469556Z Traceback (most recent call last):
2022-07-01T19:53:32.3470558Z   File "/home/conda/feedstock_root/build_artifacts/openff-toolkit-split_1656704812577/test_tmp/test_openff_toolkit.py", line 18, in <module>
2022-07-01T19:53:32.3471303Z     ff.create_openmm_system(offmol.to_topology())
2022-07-01T19:53:32.3473099Z   File "/home/conda/feedstock_root/build_artifacts/openff-toolkit-split_1656704812577/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/openff/utilities/utilities.py", line 75, in wrapper
2022-07-01T19:53:32.3474249Z     return function(*args, **kwargs)
2022-07-01T19:53:32.3475927Z   File "/home/conda/feedstock_root/build_artifacts/openff-toolkit-split_1656704812577/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 1110, in create_openmm_system
2022-07-01T19:53:32.3477243Z     interchange = self.create_interchange(
2022-07-01T19:53:32.3478604Z   File "/home/conda/feedstock_root/build_artifacts/openff-toolkit-split_1656704812577/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/openff/utilities/utilities.py", line 71, in wrapper
2022-07-01T19:53:32.3479651Z     raise MissingOptionalDependencyError(library_name=package_name)
2022-07-01T19:53:32.3480942Z openff.utilities.exceptions.MissingOptionalDependencyError: The required openff.interchange module could not be imported. Try installing the package by running `conda install -c conda-forge openff-interchange`
2022-07-01T19:53:34.1068265Z Tests failed for openff-toolkit-0.11.0rc1-pyhc2fc6b4_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
2022-07-01T19:53:34.1069799Z WARNING:conda_build.build:Tests failed for openff-toolkit-0.11.0rc1-pyhc2fc6b4_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
2022-07-01T19:53:34.1458247Z TESTS FAILED: openff-toolkit-0.11.0rc1-pyhc2fc6b4_0.tar.bz2
2022-07-01T19:53:39.5126853Z ##[error]Bash exited with code '1'.
2022-07-01T19:53:39.5192557Z ##[section]Finishing: Run docker build
```

This is the expected result; the Interchange builds aren't up yet, but we chose to make these first. An iteration or two should fix this.

**Comment by mattwthompson** [comment]
But we decided to comment it out in order to let the builds complete.

**Review by j-wags — APPROVED** [review]
LGTM!

**Pull request merged**
